# Smart Test Execution Pre-Commit Hook (PowerShell)
# Analyzes changed files and determines appropriate test execution strategy
#
# Usage: Place in .git/hooks/pre-commit.ps1 and configure Git to use PowerShell hooks

Write-Host "🔍 Analyzing changes for smart test execution..." -ForegroundColor Cyan

# Configuration
$SMOKE_TESTS = "@smoke"
$CRUD_TESTS = "@crud"
$FILTERING_TESTS = "@filtering"
$SORTING_TESTS = "@sorting"
$RESPONSIVE_TESTS = "@responsive"
$PWA_TESTS = "@pwa"
$PERFORMANCE_TESTS = "@performance"
$ACCESSIBILITY_TESTS = "@accessibility"

# File pattern to test tag mapping
$FILE_TAG_MAP = @{
    "song-library" = "@crud"
    "add-song" = "@crud"
    "edit-song" = "@crud"
    "delete-song" = "@crud"
    "filter" = "@filtering"
    "sort" = "@sorting"
    "responsive" = "@responsive"
    "mobile" = "@responsive"
    "pwa" = "@pwa"
    "service-worker" = "@pwa"
    "performance" = "@performance"
    "accessibility" = "@accessibility"
}

# Get list of changed files
$CHANGED_FILES = git diff --cached --name-only

Write-Host "📋 Changed files detected:" -ForegroundColor Yellow
$CHANGED_FILES | ForEach-Object { Write-Host "   $_" }

# Initialize test tags to run
$TAGS_TO_RUN = $SMOKE_TESTS
$ADDITIONAL_TAGS = @()

# Analyze changed files and determine additional test tags
foreach ($file in $CHANGED_FILES) {
    $filename = (Split-Path -Leaf $file).ToLower()
    
    # Check each pattern in our mapping
    foreach ($pattern in $FILE_TAG_MAP.Keys) {
        if ($filename -like "*$pattern*") {
            $tag = $FILE_TAG_MAP[$pattern]
            if ($ADDITIONAL_TAGS -notcontains $tag) {
                $ADDITIONAL_TAGS += $tag
                Write-Host "🎯 File '$file' matches pattern '$pattern' -> Adding tag: $tag" -ForegroundColor Green
            }
        }
    }
}

# Combine smoke tests with additional tags
if ($ADDITIONAL_TAGS.Count -gt 0) {
    $TAGS_TO_RUN = "$SMOKE_TESTS|$($ADDITIONAL_TAGS -join '|')"
} else {
    $TAGS_TO_RUN = $SMOKE_TESTS
}

Write-Host ""
Write-Host "🚀 Test Execution Plan:" -ForegroundColor Cyan
Write-Host "   Smoke Tests: Always run ($SMOKE_TESTS)" -ForegroundColor White
if ($ADDITIONAL_TAGS.Count -gt 0) {
    Write-Host "   Additional Tags: $($ADDITIONAL_TAGS -join ', ')" -ForegroundColor White
}
Write-Host "   Final Tag Pattern: $TAGS_TO_RUN" -ForegroundColor Yellow
Write-Host ""

# Create Jenkins trigger file with test parameters
$triggerContent = @"
# Jenkins CI/CD Trigger Configuration
# Generated by pre-commit hook on $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')

TEST_SUITE=smart-execution
TAGS_TO_RUN=$TAGS_TO_RUN
CHANGED_FILES<<DELIMITER
$($CHANGED_FILES -join "`n")
DELIMITER
GENERATE_REPORTS=true
TRIGGER_TYPE=pre-commit
COMMIT_HASH=$(git rev-parse HEAD)
AUTHOR=$(git config user.name)
BRANCH=$(git rev-parse --abbrev-ref HEAD)
TIMESTAMP=$(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')
"@

$triggerContent | Out-File -FilePath ".jenkins-trigger" -Encoding UTF8

Write-Host "✅ Jenkins trigger configuration created (.jenkins-trigger)" -ForegroundColor Green

# Optional: Run quick smoke tests locally (uncomment if desired)
# Write-Host "🧪 Running smoke tests locally..." -ForegroundColor Yellow
# & npx playwright test --grep "@smoke" --project=chromium --reporter=line

Write-Host ""
Write-Host "🎉 Pre-commit analysis complete!" -ForegroundColor Green
Write-Host "   Jenkins will execute: $TAGS_TO_RUN" -ForegroundColor White
Write-Host "   Full regression scheduled for off-hours" -ForegroundColor White
Write-Host ""

exit 0